### ISSUE TITLE
Deploy  Fallido

### ISSUE THREAD

**Issue by drnachio** [BinPar/SurvivalCTO#1]
Con un nivel de importancia casi igual a cero, no he sido capaz de hacer deploy.

¿Alguna idea?

**Comment by miguel-rr** [comment]
No has sido capaz y no te ha dado ningún error para añadirlo a la issue?
😛

**Comment by Mgonand** [comment]
Hachacitos internos?

**Comment by miguel-rr** [comment]
Nos aburrimos mucho sin ti... y alguien tendrá que dar caña

**Comment by Mgonand** [comment]
Jajajaja, ya me imagino, ya.

**Comment by drnachio** [comment]
Como os veo entretenidos:

![image](https://user-images.githubusercontent.com/5763165/35588982-9e7e2efe-0602-11e8-9117-d2646ff7ed61.png)

Para que lo disfrutes.

**Comment by drnachio** [comment]
:) Espero inquieto los comentarios de @miguelBinpar sobre el error 👍

**Comment by miguel-rr** [comment]
jajajajajaja

Pues está claro, la culpa es de la librería docker...

Fuera coñas, nunca había visto este error. Dice que no encuentra la docker-image pero hasta donde yo sé se la descarga y nunca hemos tenido problemas con eso... así que ni idea, es terreno de Marcos.

Es probable que eliminar el Container y hacer "mupx setup" y "mupx deploy" pudiera funcionar, pero no me jugaría nada...

**Comment by Mgonand** [comment]
No preocuparse, como todo en la informática, apaga y arranca de nuevo y a ver si tira. XD

(era tema de un error detectado el otro día y arreglado en el API subido a diana pero no a DIVA)
